import { Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/HeaderComp";
import Footer from "@/components/footer/FooterComp";
import BackToTopComp from "@/components/backtotop/BacktoTopComp";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],  
  variable: "--font-playfair",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfair.variable} antialiased px-6 sm:px-10 md:px-14 lg:px-20`}
      >
        <Header />
        <main className="flex flex-col gap-10 md:gap-20">
          {/* <main className="flex flex-col pb-20 gap-10 md:gap-20 mt-20 md:mt-28"> */}
          {children}
        </main>
        <Footer />
        <BackToTopComp />
      </body>
    </html>
  );
}
